<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Individual</name>
   <tag></tag>
   <elementGuidId>1bc36e30-c625-4a89-88fc-1718e53c827b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = ' Individual ' or . = ' Individual ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Individual&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1a5ef425-a4a3-4ae8-b1ab-f3e187801b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>52920e86-d62e-41e6-b8b8-40d7b336f039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Individual </value>
      <webElementGuid>3928cd17-5b46-4d9b-9bf0-1b2c0eb6e5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-250&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>26a0e375-d440-4ef5-8b97-169711cb7cca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-250']/span</value>
      <webElementGuid>01f97843-3876-4a78-b07c-f54f348c66e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start Over'])[1]/following::span[3]</value>
      <webElementGuid>d77fa84f-7ec7-439e-b80d-d2f68f1c34c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name Of The Person (As Per BRN)'])[2]/preceding::span[1]</value>
      <webElementGuid>8fa84e5d-3470-4394-b633-f921ee103b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outlet Business Type'])[2]/preceding::span[1]</value>
      <webElementGuid>f1c6d127-b4ee-4ae6-a145-902b6fecfc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Individual']/parent::*</value>
      <webElementGuid>3008f785-8112-43be-903f-2a0c03ee85af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option/span</value>
      <webElementGuid>3fc72684-d222-4620-8b5d-6b5bec46039e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Individual ' or . = ' Individual ')]</value>
      <webElementGuid>3dc8cd43-5e92-47d4-b428-ea57906b570d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
