<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No_mat-select-arrow_Emp_Type</name>
   <tag></tag>
   <elementGuidId>94c0a89a-9b07-488c-a0c5-c872ff7d39e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//mat-select/div/div[2]/div)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c88-166</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0de39b8-73aa-4a87-afd2-da4776a0a28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c88-166</value>
      <webElementGuid>cc2bc440-66b5-4d60-b491-adfef7c8a0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-38&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c88-166&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c88-166&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c88-166&quot;]</value>
      <webElementGuid>a8d43cb1-993a-4da1-8055-a47b286085ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-38']/div/div[2]/div</value>
      <webElementGuid>277947a5-6a60-4673-8441-f198af6230bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]/div</value>
      <webElementGuid>73793703-ce2b-4724-907a-a1ae02c69881</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
