<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dividend</name>
   <tag></tag>
   <elementGuidId>ff7ecfb9-eba2-44a8-bb44-ce9a0375c5ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[text()='Queries']/parent::button/ancestor::workflow-step-header/following-sibling::div[1]/div/app-credit-scorecard/div/div/app-scorcard-input-output/div[2]/div/ul/li[18]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
