<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Proof of Address of UBO(Dated less tha_19df6b</name>
   <tag></tag>
   <elementGuidId>0c01bacd-e713-44c1-b67a-21332c1c9e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-770']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-770 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>afddacb0-7ac5-4fa8-ae11-f127b492c11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>42fdae14-7a6e-47fa-8f0d-03da36aa4fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proof of Address of UBO(Dated less than 3 Month)* </value>
      <webElementGuid>66b8a005-a56f-4fae-9433-f332415636e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-770&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>64c9051b-83d6-4438-9c03-f6e6ede62d29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-770']/span</value>
      <webElementGuid>29bf0ef5-c224-49b5-a78b-54c0ab4c1557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proof of Address of Directors (Dated less than 3 Month)*'])[1]/following::span[1]</value>
      <webElementGuid>3eccfa0e-2565-4872-84cf-448cb7cba5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proof of Address of Place of Business (Dated less than 3 Month)*'])[1]/following::span[2]</value>
      <webElementGuid>e93ec0b0-38f4-43bb-b452-eb5e92b14d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proof of Address of Shareholders (Dated less than 3 Month)*'])[1]/preceding::span[1]</value>
      <webElementGuid>3bce7fc2-5869-4812-9663-8624019cd5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proof of Address of Authorised Signatories (Dated less than 3 Month)*'])[1]/preceding::span[2]</value>
      <webElementGuid>76b802ba-a058-4851-a2e2-d8789cda637e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Proof of Address of UBO(Dated less than 3 Month)*']/parent::*</value>
      <webElementGuid>1cca34b9-adac-4dd8-84c9-e57a5329802c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[5]/span</value>
      <webElementGuid>5ee7639c-14d9-4d17-a349-aa5cb7fc1d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Proof of Address of UBO(Dated less than 3 Month)* ' or . = 'Proof of Address of UBO(Dated less than 3 Month)* ')]</value>
      <webElementGuid>b0a2427b-2aa8-4444-ba95-224f6f933c01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
