<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-select-value-25</name>
   <tag></tag>
   <elementGuidId>541c329c-12e3-49f6-81d8-ea96cfbc2340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;mat-form-field-label-39\ mat-select-value-25&quot;] .mat-select-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'mat-form-field-label-39 mat-select-value-25']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-25</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5839b389-1e1b-4568-82e6-4ea3630e374f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c92-133</value>
      <webElementGuid>7fe00318-33f0-4db6-9a3e-2d816a043b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-25</value>
      <webElementGuid>0bc9bf70-43ad-4b63-949f-194b19822ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mat-select-value-25</value>
      <webElementGuid>6ad760fc-3b2f-4fb8-915c-371dcfc2997c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-50fba82732c0614ce981842e0f40b491</value>
      <webElementGuid>51f21dd2-e112-4c35-bd93-dd6530b649fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-39 mat-select-value-25']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>916006c0-f708-4d96-bc82-349100ce8f9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-39 mat-select-value-25']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>0b50aca6-62ee-4b44-9911-02f9d051c6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-25' and (text() = 'mat-select-value-25' or . = 'mat-select-value-25')]</value>
      <webElementGuid>8fe1b6f2-6cca-4d1a-93fb-406e8be581b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
