<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-select-value-139</name>
   <tag></tag>
   <elementGuidId>868f7817-c444-44fb-a17a-445ddd61369e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;mat-form-field-label-337\ mat-select-value-139&quot;] .mat-select-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'mat-form-field-label-337 mat-select-value-139']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-139</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e2e24ae2-1301-41b7-87e0-e2770dd991d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c92-365</value>
      <webElementGuid>0f4a4a14-000c-4366-9211-0bb6726d1816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-139</value>
      <webElementGuid>9ee86e86-e962-4774-b4c9-9137d65aea7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mat-select-value-139</value>
      <webElementGuid>1d45dd87-5d31-4665-a598-dc6750bbb9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-14fab204708fb658944f97140fee2143</value>
      <webElementGuid>5a854449-42bb-4f97-9c84-119250656295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-337 mat-select-value-139']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>1660f90a-828c-47a5-a384-b8222f40ad6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-337 mat-select-value-139']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>b50d79af-1d0e-44c6-b718-98d49645ca9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-139' and (text() = 'mat-select-value-139' or . = 'mat-select-value-139')]</value>
      <webElementGuid>201f7fe0-a4ee-44cc-833d-0ed39b165025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
