<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create</name>
   <tag></tag>
   <elementGuidId>7852f909-eff5-4945-93a2-69e56c587fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.mat-primary.mat-flat-button[color=&quot;primary&quot;][mat-flat-button=&quot;&quot;][_ngcontent-tuv-c288=&quot;&quot;] .mat-button-wrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ') and (@color = 'primary') and (@mat-flat-button = '') and (@_ngcontent-tuv-c288 = '')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-button-wrapper ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Create&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91d934ed-01b6-4652-ac64-02ab099d87f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>60044187-5583-45ea-98de-6eee91a09b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>9bc50b3a-b6e1-451e-857e-184d06cdee69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>82ef1327-272e-4dbe-adc5-3b233e2f146c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1e55b4453c93789d4da1d32478fba36c</value>
      <webElementGuid>093d5908-2b7c-43df-bffe-ae4289177a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ') and (@color = 'primary') and (@mat-flat-button = '') and (@_ngcontent-tuv-c288 = '')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-button-wrapper ')]</value>
      <webElementGuid>78b8027f-25e1-489d-aa0f-cff0b8cf9376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ') and (@color = 'primary') and (@mat-flat-button = '') and (@_ngcontent-tuv-c288 = '')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-button-wrapper ')]</value>
      <webElementGuid>b30786dc-fb92-42ff-b893-64dfb9a15572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>b978b99a-d788-4d34-a04f-53da7a18b29a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
