<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Office Address Line 1</name>
   <tag></tag>
   <elementGuidId>c67346f9-37b5-4c33-8049-83d25624475e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ng-star-inserted.w-full[_ngcontent-tuv-c379=&quot;&quot;]:nth-child(1) textarea.mat-form-field-autofill-control.ng-valid.ng-untouched.ng-pristine.ng-star-inserted[aria-required=&quot;false&quot;][cdktextareaautosize=&quot;&quot;][autocomplete=&quot;new-password&quot;][matinput=&quot;&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ng-star-inserted ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@_ngcontent-tuv-c379 = '') and (name() = 'span') and (position() = 1)]//textarea[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-form-field-autofill-control ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-valid ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-untouched ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-pristine ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-star-inserted ') and (@aria-required = 'false') and (@cdktextareaautosize = '') and (@autocomplete = 'new-password') and (@matinput = '')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Office Address Line 1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e73e7f27-b803-4f98-8337-3d087c555ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ac39e35b-5c34-4d20-ad95-dfc3248ba86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>c02f3a4f-0b66-4a0c-9d16-e61a6b99d536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizeminrows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b0b46668-5d99-4943-b7c3-c34b953260cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizemaxrows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>64ab0821-9525-44b4-9e69-86df03a0b97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-textarea-autosize single-line-textarea ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored ng-star-inserted</value>
      <webElementGuid>26313fc8-e7fe-4989-a24e-3c6bac81518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>office_address_line1</value>
      <webElementGuid>8f159bc8-9c3c-4dc2-9e3d-7a21f1d5dfbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9348a09-d58e-4f34-8a2b-d494e06c9292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86ebcfa7-c136-44da-9c00-a4c541fd4f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Office Address Line 1</value>
      <webElementGuid>cb8e7f23-b94f-4c4e-a91f-a3ae460f477d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1f93d3ef0bddf10bfb1089e2f25dd263</value>
      <webElementGuid>baccc78c-5c05-4568-95af-904cd7fd7313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ng-star-inserted ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@_ngcontent-tuv-c379 = '') and (name() = 'span') and (position() = 1)]//textarea[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-form-field-autofill-control ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-valid ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-untouched ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-pristine ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-star-inserted ') and (@aria-required = 'false') and (@cdktextareaautosize = '') and (@autocomplete = 'new-password') and (@matinput = '')]</value>
      <webElementGuid>45d3b95d-291d-4f44-bafc-41cb1ec87cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' ng-star-inserted ') and contains(concat(' ', normalize-space(@class), ' '), ' w-full ') and (@_ngcontent-tuv-c379 = '') and (name() = 'span') and (position() = 1)]//textarea[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-form-field-autofill-control ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-valid ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-untouched ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-pristine ') and contains(concat(' ', normalize-space(@class), ' '), ' ng-star-inserted ') and (@aria-required = 'false') and (@cdktextareaautosize = '') and (@autocomplete = 'new-password') and (@matinput = '')]</value>
      <webElementGuid>b51f3d29-a704-437a-bc79-0e9c55fcb764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'office_address_line1' and (text() = 'Office Address Line 1' or . = 'Office Address Line 1')]</value>
      <webElementGuid>459dc865-915a-4eaa-a158-c9222d49b521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
