<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Years of Stay</name>
   <tag></tag>
   <elementGuidId>8022c5cf-8f02-4bba-8696-e128763cbd5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#p_years_of_stay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'p_years_of_stay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Years of Stay*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ec794ba9-d898-40cd-9414-20f32323face</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>acdd5e77-7e2e-4385-9b79-8bf09b870020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>9559f52a-d086-447a-a939-79cc9888862d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizeminrows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>689c1deb-806e-4776-979c-1b34f888876d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizemaxrows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0dcdb409-3401-4eb8-81b0-8046ab241368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-textarea-autosize single-line-textarea numeric-textarea ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>dd3906d5-8539-4089-aef5-072f4ba5ba23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>p_years_of_stay</value>
      <webElementGuid>96f6e50d-0584-4dd5-931e-4fad22c13e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8ef71b05-ca32-4e3b-83b6-899fd86b0461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Years of Stay</value>
      <webElementGuid>856ec999-71d3-414a-a9c6-05ed7824d33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f4fa9d325dcea699fdec8d6b79dcf00</value>
      <webElementGuid>7b7a1676-edcd-478f-b1da-fe6a694ae173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'p_years_of_stay']</value>
      <webElementGuid>84efedb9-0786-4c1c-b3f6-e634d7fc9d87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'p_years_of_stay']</value>
      <webElementGuid>77ab5399-c57c-4d0f-8fd0-52ba89d047cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'p_years_of_stay' and (text() = 'Years of Stay' or . = 'Years of Stay')]</value>
      <webElementGuid>a4855e64-fb30-4b86-8da1-4f8979e760f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
