<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SBM LTD</name>
   <tag></tag>
   <elementGuidId>b0e79436-aa3e-47bf-9a02-038bcd98c6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-491']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-491 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a965adb7-514a-4807-8120-6be8e581facf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>82c53537-fdc6-4b3b-b146-6826ac6e8d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> SBM LTD </value>
      <webElementGuid>56b85e39-7065-4739-a1a3-0a89a2c5e593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-491&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>afecaa8e-84bc-4822-9688-7e91c4c2fd50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-491']/span</value>
      <webElementGuid>c3c784d7-6604-41b4-bf91-db216f4da77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAUBANK'])[1]/following::span[1]</value>
      <webElementGuid>078aadef-351c-42d5-8c80-1fc49bd758d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HONG KONG &amp; SHANGHAI BANKING CORPORATION'])[1]/following::span[2]</value>
      <webElementGuid>1864002c-8b92-4c42-8e40-649cd1c1ca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SBI INTERNATIONAL (MAURITIUS)'])[1]/preceding::span[1]</value>
      <webElementGuid>e38e1eed-4472-4285-a7da-e065051c78b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STANDARD BANK (MAURITIUS) LTD'])[1]/preceding::span[2]</value>
      <webElementGuid>da72417e-2320-4a12-b55b-27f7c8fbb7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SBM LTD']/parent::*</value>
      <webElementGuid>bd58b6e7-14e6-41a3-b166-b347f5bcce81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[10]/span</value>
      <webElementGuid>c5f9d434-ab22-4937-96d5-6ec3c62f3d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' SBM LTD ' or . = ' SBM LTD ')]</value>
      <webElementGuid>8ea21dbf-5f4c-47d4-a576-8e64a95573d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
