<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vat Certification</name>
   <tag></tag>
   <elementGuidId>c5a30ae7-d281-41bf-a50b-dc2ad88eb4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-499']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-499 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>de71991c-5e03-427f-8cf1-d76b66bec51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>05ed158f-81d7-408a-b21d-6b3189ac22f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vat Certification</value>
      <webElementGuid>d566f84a-1725-48a5-803f-c4b4d0330f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-499&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>2a7fa60f-a595-4ef2-a74b-593daa846162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-499']/span</value>
      <webElementGuid>7d77da08-6a88-42f5-afd6-a6fadddd843a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid Trade License'])[1]/following::span[1]</value>
      <webElementGuid>498dc4d0-0639-4fa1-b1b9-ed3d784d8f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Registration Card*'])[1]/following::span[2]</value>
      <webElementGuid>15fe2e8a-7d37-43d5-95c0-ca8833ab92de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank Account Evidence*'])[1]/preceding::span[1]</value>
      <webElementGuid>0c22a298-7a2d-4359-857d-42748cee4a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other License'])[1]/preceding::span[2]</value>
      <webElementGuid>a2d7fd22-5cc1-49e8-a3da-a14b8668dd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vat Certification']/parent::*</value>
      <webElementGuid>a78cc1bd-f723-4671-bc21-2cfb1936a0b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[3]/span</value>
      <webElementGuid>15364972-c7af-4ca1-b587-27f0d2f4000f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Vat Certification' or . = 'Vat Certification')]</value>
      <webElementGuid>255ac9db-0655-4f30-9191-37d949e90d84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
