<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Merchants</name>
   <tag></tag>
   <elementGuidId>0b0de274-8be9-4a4c-921d-2243260ee005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//span[contains(text(),'Merchants')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
