<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add New Identifier_mat-select-arrow ng-_fe449a</name>
   <tag></tag>
   <elementGuidId>2ce86f22-d324-421c-85de-3ff565ff1600</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-40']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c90-122</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2bff09b7-b1ec-4109-806c-b1492db24081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c90-122</value>
      <webElementGuid>c4a4a65f-fa10-4144-bb0d-9a49f709c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-40&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c90-122&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c90-122&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c90-122&quot;]</value>
      <webElementGuid>921f875e-4eab-4576-b50e-2e882454cb2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-40']/div/div[2]/div</value>
      <webElementGuid>12b90f62-a07f-43b4-9b30-1cc7aae9904c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-select/div/div[2]/div</value>
      <webElementGuid>f2a23000-3f34-4c2f-bdee-255769b9fe76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
