<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CHINA TOWN</name>
   <tag></tag>
   <elementGuidId>21b3850f-2658-475a-ab20-6ca1d515d09a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-229']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-229 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd23b6d1-1c6f-4ac7-b78a-eae41067d856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>fb89b041-da70-4636-aaba-482ca4881b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CHINA TOWN </value>
      <webElementGuid>6c32dbe4-2908-432d-b0ce-bfe88c6ceef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-229&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>b5114296-be92-4c68-a630-d275d1864427</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-229']/span</value>
      <webElementGuid>aa1ab4f3-234f-4287-b3fb-c362a248c897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAMPS DE MARS'])[1]/following::span[1]</value>
      <webElementGuid>2de70907-d4ea-4cd0-958a-b4a6c7347f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CASSIS'])[1]/following::span[2]</value>
      <webElementGuid>3e9346da-f69e-414f-849c-d58f4e84f494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITE LA CURE'])[1]/preceding::span[1]</value>
      <webElementGuid>71e266fa-154c-4319-884e-70e96d206f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CITE MARTIAL'])[1]/preceding::span[2]</value>
      <webElementGuid>3ca3c34d-ca24-4ee7-801f-4ef4c37b57fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CHINA TOWN']/parent::*</value>
      <webElementGuid>40bda67a-194c-48b9-8122-85f482bc033b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[7]/span</value>
      <webElementGuid>751e52ee-feff-4420-8472-be88ade96e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' CHINA TOWN ' or . = ' CHINA TOWN ')]</value>
      <webElementGuid>8bdbf52c-c41b-4e73-98f6-b4120320a774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
