<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Documents - KYC - Sole Trader-Sub Type__173058</name>
   <tag></tag>
   <elementGuidId>602736a5-29f3-4d01-8076-1f5196d80af6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-label[contains(text(),'Sole Trader-Sub Type2')]/ancestor::span/preceding-sibling::mat-select[@role='combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3602095-8e86-4a90-947a-836e1fad446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c90-15</value>
      <webElementGuid>d41916ed-a021-48dc-8e47-db2fe1b0ba96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-9</value>
      <webElementGuid>af00ac0e-c4b1-46bd-8100-d31c1fdcbaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-9&quot;)</value>
      <webElementGuid>e5aaf701-585a-44e6-86c8-e11712e6e69e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-9']</value>
      <webElementGuid>65fd351f-7a53-4d36-ac04-32a0850e697b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-8']/div/div</value>
      <webElementGuid>26a8c479-fbb0-4834-b482-42fcadaf173f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents - KYC - Sole Trader-Sub Type'])[1]/following::div[10]</value>
      <webElementGuid>c26cee17-0e78-49a0-884f-33aba68b2017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National Identity Card*'])[1]/following::div[12]</value>
      <webElementGuid>4d6c8d59-4a90-4400-8577-d2139cdd2fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents - KYC - Sole Trader-Sub Type2'])[1]/preceding::div[3]</value>
      <webElementGuid>171b2b2c-e05c-4c3e-822b-6be05197d32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Name'])[1]/preceding::div[7]</value>
      <webElementGuid>256ffff3-1a0e-4a19-837c-a0ec614d01b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>e8e2d16e-2805-43cf-a398-4ec7a3bc5112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-9']</value>
      <webElementGuid>fe61709d-dc9a-4752-8f07-c10df43d02e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
