<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fee Value_feeValue</name>
   <tag></tag>
   <elementGuidId>0ac1a66e-e139-44d0-9638-0e1accf30cf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'outlined')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#outlined-adornment-weight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9421391d-decd-4690-bf17-04cb1541d205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outlined-adornment-weight</value>
      <webElementGuid>5c71ab0a-b497-4eb1-96a2-8f25c36ccbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feeValue</value>
      <webElementGuid>d9f11810-718e-44f4-8a1b-af489728d296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>4c77335f-b022-48f4-8f7d-6412b604a466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e29c8a95-7ba8-4b48-88ed-471f89dcdc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input css-1x5jdmq</value>
      <webElementGuid>4151eda4-af30-423b-9916-537df0cc8048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outlined-adornment-weight&quot;)</value>
      <webElementGuid>26009cd6-1e7b-456d-a271-006144ea5458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='outlined-adornment-weight']</value>
      <webElementGuid>4d04864b-64c3-4932-a051-09d83541f5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>0ff9eb58-5ddc-4c38-a5b7-03a1ee696e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'outlined-adornment-weight' and @name = 'feeValue' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>58464dc8-e29e-4c2b-8786-1d00c5271917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
