<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RegisteredAddress</name>
   <tag></tag>
   <elementGuidId>8844cb2d-139b-4235-98fe-260f2850507e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div//textarea[@id=&quot;business_address_line_1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
