<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Flat</name>
   <tag></tag>
   <elementGuidId>67e792e4-d867-48ed-b924-affe1e290d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkboxes-tags-demo-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text() = 'Flat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5ba4c9cb-b4ed-42c0-a22e-b8b543b980e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3cc5f075-8b06-4043-8526-2285680d84e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>74079ed1-9da3-440b-9f20-a21767e84cee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkboxes-tags-demo-option-1</value>
      <webElementGuid>2a292b62-89e1-4aaa-a88b-bcf15ed42413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7f996846-7065-4641-9b94-d9615e2b376e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ac466bf6-9f1c-419d-bb55-9a2dfa106a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e00299aa-ef44-43a2-a678-37da491fc259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>3f3f96d8-b8b8-4dac-b7e8-fa83b914f130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Flat</value>
      <webElementGuid>a90a9ea4-cbca-47d6-8377-776af3cbbbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkboxes-tags-demo-option-1&quot;)</value>
      <webElementGuid>d40f262e-603d-4eb3-9641-a0927cbc6622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='checkboxes-tags-demo-option-1']</value>
      <webElementGuid>a8752d56-f54c-464e-b322-fe2f899844af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='checkboxes-tags-demo-listbox']/li[2]</value>
      <webElementGuid>493fea6d-63b9-4a9d-8f33-906c89974acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Percentage'])[1]/following::li[1]</value>
      <webElementGuid>776f76e6-5700-430e-9506-1e4962a71a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::li[2]</value>
      <webElementGuid>69ce01df-69eb-4d76-9b41-3628ebc5c0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Flat']/parent::*</value>
      <webElementGuid>c4e78091-2db9-4ea7-b844-8b15296e2368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>992f300d-aa88-48f1-9acd-0f1dc8f25ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'checkboxes-tags-demo-option-1' and (text() = 'Flat' or . = 'Flat')]</value>
      <webElementGuid>19dc9fba-16d1-41df-9556-6aedd26de7ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
