<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Register for BNPL</name>
   <tag></tag>
   <elementGuidId>0717e0eb-9493-4e15-926d-9232ab247d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mat-focus-indicator.w-full.mat-menu-item.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Register for BNPL')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec53e640-292b-4098-86a4-c50f7d464209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator w-full mat-menu-item ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>132208f4-e3ea-4de7-80b7-cfb174a8ca11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>1938e1ef-64a1-4a95-b788-e59d3c53556a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0eff89d-24f3-4bfe-9e2b-69e2147dffa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9ed0e47f-72b6-4b7a-b352-67b936ab76e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Register for BNPL </value>
      <webElementGuid>89149657-4322-48a4-ad44-4add8a608b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-4&quot;)/div[@class=&quot;mat-menu-content ng-tns-c117-9&quot;]/button[@class=&quot;flex flex-col w-full ng-tns-c117-9 ng-star-inserted&quot;]/div[@class=&quot;mat-focus-indicator w-full mat-menu-item ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>dcb6e424-e852-46c6-a024-9e23a722da42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-4']/div/button/div</value>
      <webElementGuid>a3b67762-65f2-43d4-8e5f-7561e2ae7c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JAN 2024'])[1]/following::div[9]</value>
      <webElementGuid>8f4ae1fc-ea19-469b-98bf-a699e0d19a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version:'])[1]/following::div[11]</value>
      <webElementGuid>93470a6a-f55d-490c-9cfa-9bbd1f681dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>9ad648c8-9c92-4710-8aab-00da8cda213c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Register for BNPL ' or . = ' Register for BNPL ')]</value>
      <webElementGuid>4ce890ab-b54c-4415-9c06-a291b514510f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
