<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Last Name_mat-select-arrow ng-tns-c88-21</name>
   <tag></tag>
   <elementGuidId>3ab1f760-539d-4391-865c-dc8bef6bdb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-label[text()='Gender']/ancestor::label/parent::div/mat-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c88-21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>733f7bb3-75c2-4343-ac6a-70d8271b61c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c88-21</value>
      <webElementGuid>487faa71-ab8d-4b1c-b5f2-dc4a9de1a02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-4&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c88-21&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c88-21&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c88-21&quot;]</value>
      <webElementGuid>19d92d63-e663-402c-b285-ac3341c2924d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-4']/div/div[2]/div</value>
      <webElementGuid>c7c68ec7-cddc-4ef5-a252-8691a164819f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[4]/div/div/div/mat-select/div/div[2]/div</value>
      <webElementGuid>ce58e6c6-40da-422c-a361-c11199f6f03e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
