<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//div[@id=&quot;mat-select-value-9&quot;]</description>
   <name>div_sourcing_channel</name>
   <tag></tag>
   <elementGuidId>e7eb4437-f757-4e53-b705-a5ba50cb70ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;mat-select-value-9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
