<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Proceed</name>
   <tag></tag>
   <elementGuidId>2fe9e36e-4dac-47e2-ba96-20634b519244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.mat-primary.mat-button.mat-flat-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-button ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Proceed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f3b2a6d-5bfa-4d11-b009-4b91e394a9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-button mat-button-base mat-primary mat-flat-button</value>
      <webElementGuid>07ed55a8-a135-4dd4-9ebd-2445957704bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>52143c17-b1a5-40df-aa51-30b832fd528c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Proceed</value>
      <webElementGuid>c01f3a64-c010-4ad4-8a37-13387486f0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-68cd8b2b51c96de8fc82de341ae8cbf8</value>
      <webElementGuid>671bab6b-f4bd-46f7-b3c7-0cd64ba649d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-button ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ')]</value>
      <webElementGuid>8af19702-4c71-49f9-988c-7a89663cc171</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-button ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ')]</value>
      <webElementGuid>eab45f8c-939c-47f3-8a57-56529f94f166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Proceed' or . = 'Proceed')]</value>
      <webElementGuid>13eb8eda-0f58-4757-87f0-359a0df6a3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
