<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-select-value-53</name>
   <tag></tag>
   <elementGuidId>89783247-c727-4363-897d-1eddcef18fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Employment Type')]/ancestor::span/parent::div/mat-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;mat-form-field-label-113\ mat-select-value-53&quot;] .mat-select-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-53</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1f4d9a3-4699-404a-bba3-9138bad5c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c92-187</value>
      <webElementGuid>6b3cf561-c615-411c-94ac-37d0e5835735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-53</value>
      <webElementGuid>7cdd20b4-2475-4fcc-b831-ebeb4d1bbe85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mat-select-value-53</value>
      <webElementGuid>aace64e4-3107-40ab-a35d-d6214568cadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fa0fb07ed599a6d096d2b7926c8db274</value>
      <webElementGuid>9e52f804-9a48-40a6-9cc7-e7fc016ce4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-113 mat-select-value-53']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>b9093df1-6b97-4daf-a258-4c1faabe9f1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-113 mat-select-value-53']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>54dd3cb6-7a01-4528-8f1d-fd14a5ad0617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-53' and (text() = 'mat-select-value-53' or . = 'mat-select-value-53')]</value>
      <webElementGuid>6f9d21e5-1c08-4c5a-9686-14af813759c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
