<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-select-value-71</name>
   <tag></tag>
   <elementGuidId>db19c116-7a0d-4c66-a3d9-484f0bf4420d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(),'Postal Code')]/ancestor::span/parent::div/mat-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;mat-form-field-label-157\ mat-select-value-71&quot;] .mat-select-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-71</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d6c2628d-24df-466b-b719-a3c8c4ec1715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c92-223</value>
      <webElementGuid>1bb2d0a2-ad2f-434d-a112-f54487f4a833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-71</value>
      <webElementGuid>461336f9-0b0f-4d8e-8edc-88c251ff5ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mat-select-value-71</value>
      <webElementGuid>483caa91-686d-476a-b854-d985933f419b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-006ead8637f049b64dc0b5bb1e4aab61</value>
      <webElementGuid>30947fa7-2e4c-4d33-a594-77badf3cf49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-157 mat-select-value-71']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>cf4cb940-5be9-46b5-aaca-77474a9216f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-157 mat-select-value-71']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>4f2c9e03-a25b-49a9-9ff0-a5fa240cce1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-71' and (text() = 'mat-select-value-71' or . = 'mat-select-value-71')]</value>
      <webElementGuid>a8e2b2e9-fd03-4cee-831d-d2e0cb3a75d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
