<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mat-select-value-131</name>
   <tag></tag>
   <elementGuidId>22def2f8-e1ac-4e27-b0ae-04c141ed2bd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;mat-form-field-label-311\ mat-select-value-131&quot;] .mat-select-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[text()='Sector']/ancestor::span/parent::div/mat-select&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#mat-select-value-131</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74d54ede-8197-4e39-a17e-decdae68a3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c92-348</value>
      <webElementGuid>d32085d2-a861-4302-9fc3-9699303b5a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-131</value>
      <webElementGuid>3c53c4c8-9782-4bd1-bf82-9c0b7fb653b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mat-select-value-131</value>
      <webElementGuid>0c78beb5-10b2-4719-9fa3-6d8f85a47c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d6b9accbbad1a5681bddee1c16badccc</value>
      <webElementGuid>3338aebc-2841-4d61-8936-8ee877704005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-311 mat-select-value-131']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>f43810d1-4fcb-4146-8a41-01a0d87dffb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'mat-form-field-label-311 mat-select-value-131']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-select-value ')]</value>
      <webElementGuid>905fd578-b016-45ea-82cc-b5b6a9ee5782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-131' and (text() = 'mat-select-value-131' or . = 'mat-select-value-131')]</value>
      <webElementGuid>907bb36f-27cd-4991-be8f-bfc5fd7c9fd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
