<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create</name>
   <tag></tag>
   <elementGuidId>4a8617a4-bd3e-4acb-a3bd-d2c4b0e571ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button//span[contains(text(),'Create')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.mat-primary.mat-flat-button[color=&quot;primary&quot;][mat-flat-button=&quot;&quot;][_ngcontent-tuv-c288=&quot;&quot;] .mat-button-wrapper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Create&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6af7b78a-02cd-4dee-8764-c27a0a595dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-button-wrapper</value>
      <webElementGuid>b8d4925a-11eb-4aea-aafc-990e97329ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>ab27d760-a23e-4775-b977-1a2616a99a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>54fcf62a-335f-4f2c-a313-baab2ea83b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1e55b4453c93789d4da1d32478fba36c</value>
      <webElementGuid>794c413f-6364-408c-b14b-0e94312aa882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ') and (@color = 'primary') and (@mat-flat-button = '') and (@_ngcontent-tuv-c288 = '')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-button-wrapper ')]</value>
      <webElementGuid>c4dea2ca-10e9-42db-a094-bc142284fbaf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' mat-flat-button ') and (@color = 'primary') and (@mat-flat-button = '') and (@_ngcontent-tuv-c288 = '')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' mat-button-wrapper ')]</value>
      <webElementGuid>84d4fea9-b9fc-421b-9eab-02e6438a374f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>cbedfc95-8b56-4709-96f0-4a1ca64f7abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
