<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Total Work Experience (Months)_</name>
   <tag></tag>
   <elementGuidId>d41410e5-1f05-4a8c-86da-bc51c4474d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total_work_expirence</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'total_work_expirence']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Total Work Experience (Months)*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9c8536e3-48fc-4c5c-ae1d-4dba588e8267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>709b459d-186d-405f-84ca-3320de742dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>9b4ebf59-7d96-492b-af15-ece482203dce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizeminrows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8073f3c5-8864-4d98-acbc-6f199c72afe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizemaxrows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>d35155ca-fc31-4ee5-8446-691414225035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-textarea-autosize single-line-textarea numeric-textarea ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>52f7f8db-b7e3-4c91-ab4a-64b4eb44f8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total_work_expirence</value>
      <webElementGuid>fb0404c4-2a51-4858-ade8-d77907297cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>00aa166d-6ef0-4320-8467-a5f3feb7d939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Total Work Experience (Months)_</value>
      <webElementGuid>d0c7d294-4524-4fab-8d6a-40a964c99d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d05427aee64ee8c2af2b2d6dd36082ee</value>
      <webElementGuid>a2e857b1-ba57-429c-acdb-737b36f78b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'total_work_expirence']</value>
      <webElementGuid>0dccc6c2-77f7-4f0b-8a14-b8c9cfca91f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'total_work_expirence']</value>
      <webElementGuid>2907197b-5577-44ff-9d90-4b47a9e79934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'total_work_expirence' and (text() = 'Total Work Experience (Months)_' or . = 'Total Work Experience (Months)_')]</value>
      <webElementGuid>eba7bcf9-f6ad-4e8e-a652-7a505ae60bb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
