<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Locality_Outlet_Details</name>
   <tag></tag>
   <elementGuidId>a0739f4f-d712-4127-b50c-a2070b320d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[contains(text(),'Locality')])[1]/ancestor::span/preceding-sibling::mat-select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-select-value-19</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>233c10b2-0640-4c17-847e-661e24205ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-value ng-tns-c90-42</value>
      <webElementGuid>e493a30e-d784-4a56-b147-8eda194e5e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-value-19</value>
      <webElementGuid>0b198f33-b436-4f2c-a517-417433a3dd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-19&quot;)</value>
      <webElementGuid>b540a8ea-87e3-4d51-9e0d-f399d2ec20e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-19']</value>
      <webElementGuid>3123209f-baa8-41f7-a395-e8da0a8bc84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-18']/div/div</value>
      <webElementGuid>69af47b1-5dc9-473f-baf0-cd6fbe8c3a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[10]</value>
      <webElementGuid>a4deb497-ff07-4162-97be-62009fafc8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District'])[1]/following::div[10]</value>
      <webElementGuid>db0c100a-6d5b-4357-9d58-f90f14b62cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locality'])[1]/preceding::div[3]</value>
      <webElementGuid>e53ddd41-55be-4075-9c85-d0a5ec756fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::div[3]</value>
      <webElementGuid>4c863d72-6e10-42e1-a129-da1af0e15cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/mat-form-field/div/div/div/mat-select/div/div</value>
      <webElementGuid>74f31b4e-2c8b-4781-861e-f673b3ba9b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-value-19']</value>
      <webElementGuid>e128c59c-720f-4294-a482-7e2b25c09ba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
