<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__acc_holder_name</name>
   <tag></tag>
   <elementGuidId>2630201e-47f8-419a-ab57-de21ed37d1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acc_holder_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='acc_holder_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db598877-41c2-4d50-9291-86c2c18ceb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>2e5fc46b-1201-4f15-8f02-212c9d06fc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored ng-star-inserted</value>
      <webElementGuid>8a245eec-0d2e-488f-92fb-71972d83cc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06154da0-47d7-498d-90eb-faa3eca4de9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acc_holder_name</value>
      <webElementGuid>971f58e8-46eb-4f54-b09a-0f5db96290f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>696d0e22-fd55-419b-a54c-a7e01a87032a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acc_holder_name&quot;)</value>
      <webElementGuid>4a867b73-70d1-4f9b-98f3-b3df15dc58c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acc_holder_name']</value>
      <webElementGuid>3c8bb913-d26c-4eb2-b6d3-20d372765b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynamicComponentParent']/source-details/div/div/div/app-update-source-detail/div/div/form/div/div[4]/mat-form-field/div/div/div/input</value>
      <webElementGuid>d0bc6761-81f2-408b-86e2-bed7efae5954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/mat-form-field/div/div/div/input</value>
      <webElementGuid>412d178f-ce02-4d40-ac27-69e319c59ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'acc_holder_name']</value>
      <webElementGuid>fc2941f9-5f01-4e6e-ab22-f6fb9e691da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
