<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Bank Statement - Business</name>
   <tag></tag>
   <elementGuidId>4b71c631-a299-404d-ad7d-a5879889f567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@role='listbox']/mat-option[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-318 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1327abfa-7c13-4e4f-ba9d-872b09fb2dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>a7ab38cd-73e0-4881-9fa0-7b67fd0930c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bank Statement - Business</value>
      <webElementGuid>56bff11c-e299-4125-b406-764588535a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-318&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>cba1d6e0-1569-42dc-892e-c7a83dc2621d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-318']/span</value>
      <webElementGuid>b0f43b85-a223-4b16-93bc-a4e33fd2bf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MTML - Place Of Business'])[1]/following::span[1]</value>
      <webElementGuid>918bfe73-0ba5-4f02-97e5-fb9c59cd4841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MYT- Place Of Business'])[1]/following::span[2]</value>
      <webElementGuid>201d1ecf-fa18-4ac7-b8d4-d0fa8be83433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rent Book - Business'])[1]/preceding::span[1]</value>
      <webElementGuid>9528b12b-f746-44d5-82b9-70103d51f029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-option-318', '&quot;', ')/span[@class=', '&quot;', 'mat-option-text', '&quot;', ']')])[1]/preceding::span[2]</value>
      <webElementGuid>d947443b-4d21-4cd4-ae7c-6ae855009908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bank Statement - Business']/parent::*</value>
      <webElementGuid>a55d0d8c-9334-4365-b4e0-1f2b6e3c8de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[6]/span</value>
      <webElementGuid>64f0d346-9fc9-470e-bd42-262f9db52bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bank Statement - Business' or . = 'Bank Statement - Business')]</value>
      <webElementGuid>66cfb906-8075-494a-8c76-48f2c90ade6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
