<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Last Name</name>
   <tag></tag>
   <elementGuidId>2d743a58-d993-404d-bd7c-954375da44e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-describedby=&quot;mat-error-9&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-describedby = 'mat-error-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Last Name*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e8139b26-91bc-4c88-8d82-8372cf7767ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3503fccc-2838-488a-9ef6-fa18847653e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>022d579b-e713-4231-9dd8-1c84ff819e35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizeminrows</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fe3e26d4-0835-43b2-b62d-f29565528281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cdkautosizemaxrows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f7cd9b60-e4e7-4789-9064-4532f28d978d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control cdk-textarea-autosize single-line-textarea ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored ng-star-inserted</value>
      <webElementGuid>5b138137-03a1-429e-be66-70b0ee00791a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifier3</value>
      <webElementGuid>46e416a8-7b20-4548-8503-0f1dfde8e51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f844c517-31ee-4d47-ae29-dd750c7fc540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>mat-error-9</value>
      <webElementGuid>70fd4714-5847-4031-87ce-1de93a8f65e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>834e4790-f673-4ff9-851d-a886d73512f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f0c387819de73e79533a9ececbc876b</value>
      <webElementGuid>8a1965d8-6a95-4d22-a486-d0cc2d23486f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-describedby = 'mat-error-9']</value>
      <webElementGuid>6ebe24d4-4397-4e99-a35e-421259c81690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-describedby = 'mat-error-9']</value>
      <webElementGuid>d0f75549-b5fb-4628-b00c-2f0bd3c4097b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'identifier3' and (text() = 'Last Name' or . = 'Last Name')]</value>
      <webElementGuid>230051b1-3612-4068-ae3b-2e50bd2d9ce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
